"""Add otp column to password_reset table

Revision ID: e3d19eaa729f
Revises: 
Create Date: 2024-03-28 14:20:41.234900

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e3d19eaa729f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('password_reset', schema=None) as batch_op:
        batch_op.add_column(sa.Column('otp', sa.String(length=6), nullable=False))
        batch_op.add_column(sa.Column('timestamp', sa.DateTime(), nullable=False))
        batch_op.drop_column('created_at')
        batch_op.drop_column('token')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('password_reset', schema=None) as batch_op:
        batch_op.add_column(sa.Column('token', sa.VARCHAR(length=100), nullable=False))
        batch_op.add_column(sa.Column('created_at', sa.DATETIME(), nullable=True))
        batch_op.drop_column('timestamp')
        batch_op.drop_column('otp')

    # ### end Alembic commands ###
